# Generated by Django 4.1.7 on 2023-03-01 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('address', models.TextField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('EM', 'Empty'), ('FL', 'Full'), ('BK', 'Booked')], default='EM', max_length=2)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parking')),
            ],
        ),
    ]
