# Generated by Django 4.1.7 on 2023-03-01 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking',
            old_name='title',
            new_name='name',
        ),
    ]
